server:
  port:
    8080
spring:
  application:
    name: mongo-demo
  data:
    mongodb:
      host: 192.168.1.201
      database: ninggc
      transactionEnabled: true

mongo:
  collection-name: test1